# Basic Site Settings
locale: "en-US"
site_theme: "default"
title: "Gaddala Sathvik"
title_separator: "-"
name: &name "Gaddala Sathvik"
description: &description "Computer Science Undergraduate | ML Enthusiast | Software Engineer"
url: "https://academicpages.github.io"
baseurl: ""
repository: "academicpages/academicpages.github.io"

# Site Author
author:
  avatar: "profile.png"
  name: "Gaddala Sathvik"
  pronouns:
  bio: "B.Tech CSE @ IIITM Gwalior | Intern @ Google | AI, Go, and Angular Dev"
  location: "India"
  employer: "ABV-IIITM Gwalior"
  uri:
  email: "gsathvik999@gmail.com"

  # Academic websites
  googlescholar: "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
  orcid: "http://orcid.org/yourorcidurl"
  pubmed: "https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"

  # Repositories and software development
  github: "sathvik73"
  stackoverflow: # optional

  # Social media
  linkedin: "in/gaddala-sathvik"
  twitter: # optional
  facebook:
  instagram:
  youtube:
  bluesky: "bsky.app"

# Publication Category
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'
  conferences:
    title: 'Conference Papers'

# Site Settings
teaser:
breadcrumbs: false
words_per_minute: 160
future: true
read_more: "disabled"
talkmap_link: false

comments:
  provider:

atom_feed:
  hide: false

# SEO
google_site_verification:
bing_site_verification:
alexa_site_verification:
yandex_site_verification:

# Social Sharing
twitter:
  username: &twitter
facebook:
  username:
  app_id:
  publisher:
og_image:

social:
  type: Person
  name: "Gaddala Sathvik"
  links:
    - "https://www.linkedin.com/in/gaddala-sathvik/"
    - "https://github.com/sathvik73"
    - "https://www.codechef.com/users/freakinturkey"
    - "https://codeforces.com/profile/sathvik_666"

# Analytics
analytics:
  provider: "false"

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor

keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Asia/Kolkata

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
